import Head from "next/head"
import Image from "next/image"
import styles from "../styles/Home.module.css"
import { getAllRestaurants, getAllRestaurantsIds } from "../lib/restaurants"
import Link from "next/link"

const Home = ({ data }) => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Restaurant List</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Restaurant List</h1>

        <p className={styles.description}>
          Get started by editing{" "}
          <code className={styles.code}>pages/index.js</code>
        </p>
        <ul>
          {data.map((elm) => (
            <li key={elm._id}>
              <Link href={`/restaurant/${elm._id}`}>
                <a>{elm.name}</a>
              </Link>
            </li>
          ))}
        </ul>
      </main>
    </div>
  )
}

export async function getStaticProps() {
  const data = await getAllRestaurants()
    .then((res) => res.data)
    .catch((err) => console.log(err))
  const paths = await getAllRestaurantsIds()
  console.log(paths)
  return {
    props: {
      data,
    },
  }
}

export default Home
